services:
  db:
    image: postgres:16-alpine
    container_name: 69-s1-db
    ports:
      - 54327:5432
    environment:
      - POSTGRES_PASSWORD=1p@ssw0rd
      - POSTGRES_USER=prawee
      - POSTGRES_DB=prawee
    volumes:
      - ./data/data:/var/lib/postgresql/data
  admin:
    image: dpage/pgadmin4
    container_name: 69-s1-admin
    ports:
      - 8081:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=prawee.w@fte.kmutnb.ac.th
      - PGADMIN_DEFAULT_PASSWORD=1p@ssw0rd
  app:
    image: prawee/strapi
    container_name: 69-s1-app
    ports:
      - 8181:1337
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_NAME=prawee
      - DATABASE_HOST=172.30.113.245
      - DATABASE_PORT= 54327
      - DATABASE_USERNAME=prawee
      - DATABASE_PASSWORD=1p@ssw0rd
